DNA_CODON_TABLE = {
    'TTT': 'F', 'CTT': 'L', 'ATT': 'I', 'GTT': 'V',
    'TTC': 'F', 'CTC': 'L', 'ATC': 'I', 'GTC': 'V',
    'TTA': 'L', 'CTA': 'L', 'ATA': 'I', 'GTA': 'V',
    'TTG': 'L', 'CTG': 'L', 'ATG': 'M', 'GTG': 'V',
    'TCT': 'S', 'CCT': 'P', 'ACT': 'T', 'GCT': 'A',
    'TCC': 'S', 'CCC': 'P', 'ACC': 'T', 'GCC': 'A',
    'TCA': 'S', 'CCA': 'P', 'ACA': 'T', 'GCA': 'A',
    'TCG': 'S', 'CCG': 'P', 'ACG': 'T', 'GCG': 'A',
    'TAT': 'Y', 'CAT': 'H', 'AAT': 'N', 'GAT': 'D',
    'TAC': 'Y', 'CAC': 'H', 'AAC': 'N', 'GAC': 'D',
    'TAA': 'STOP', 'CAA': 'Q', 'AAA': 'K', 'GAA': 'E',
    'TAG': 'STOP', 'CAG': 'Q', 'AAG': 'K', 'GAG': 'E',
    'TGT': 'C', 'CGT': 'R', 'AGT': 'S', 'GGT': 'G',
    'TGC': 'C', 'CGC': 'R', 'AGC': 'S', 'GGC': 'G',
    'TGA': 'STOP', 'CGA': 'R', 'AGA': 'R', 'GGA': 'G',
    'TGG': 'W', 'CGG': 'R', 'AGG': 'R', 'GGG': 'G'
}


def protein(s):
    protein = ''

    lines = s.split()
    dna = lines[0]
    introns = lines[1:]

    for intron in introns:
        dna = dna.replace(intron, '')

    for i in range(0, len(dna), 3):
        codon = dna[i:i + 3]

        amino = ''
        if codon in DNA_CODON_TABLE:
            amino = DNA_CODON_TABLE[codon]

        if amino == 'STOP':
            break

        if amino:
            protein += amino

    return ''.join(protein)



print (protein("""
ATGGGATACAACGCCTTTGGAGACTCTGTCGACACCAGAAACAATATGCGGTTGGAGTAAAGATGCATATCAGTCTCTGATCGATGGGGTCGATCCCACACGAATGGTAAGTCTTAGGGCGGCAACCTAGCATCGATATCATTTGACTAGGTTTGACCGCCCGGGATTGCTTCTTCTGGATGGTCCGCTCACTTTTTAGTGATCTCGCTATATCTCGGTTCCAGATTTTACCCACCCCGACGACGCTCCAAGGGTAACAGAAGTCCCGCTCTTCGCATAACGGCTAGAAGCTGGTATTTGTGTTGAATCGTGGCCATTTGCGGATGGCACATAATAGTCAGGTCTTTTTTTTCCAGAGTTAGCTTGGAGCCTATGAGACCGCTTTGAGCATGATTGGGCTAGACCGCCCTCCATGTTCTAGTGACATAAACATGCTAGTCAGTGCGTGGAAGATTGCCCCATGGCTATATTCTCCCTAGTACGATCCAACACTCTATCCTTCTGCCGTAAACTTAGGGTTACTGAAGGCAAATGAGCCAAAAACCTTGATATACGTCGTCTGGGCTTATAACGGCAATACCCGTTCGGCTGTTCCATTGTCAGATGCTTTCCTTTGCCGGCGTCCTCTGCGAACGTTGATGCAAAAGCTAAGTACTCCCATTGGCCCTGGAACCAACGGCAACGTCTAAAGATGTACCCTGCGCATACATGCAGGGCTCTCACTCCACGTTTATCAGCTCGGGTCAGGGACTCCATAGTAGTGCCAGATTGGCAAGTTCAAGAGGGAGGGTGTGAACCCGCCTACGTGTTATCCCATATGGAATTATAAATACGGCACTAATGCAAGCCCATATACACTACACTGGGGTCAAAATGCGTAGTCGTTGTGCCAGTCTGCTCGTTGAGCGTCCGCGATTATTAACTGCTGAAGTCTTCTGGGTGTTCTGCGTCCTTGCTCAGTAA
AGTTAGCTTGGAGCCTATGAG
GTAAGTCTTAGGGCGGCAACCTAGCATCGATATCATTTGACTAGGTTTG
CCATGTTCTAGTGACATAAACATGCTAGTCAGTGCGTGGAA
TTCTGCCGTAAACTTAGGGTTACTGAAGGCAAAT
CGGTTCCAGATTTTACCCACCCCGACGACGCTCCAAGGGTAACAG
CGTTTATCAGCTCGGGTCAGGGACTCCATAGTAGTGCCAGATTGGC
GCTGTTCCATTGTCAGATGCT
GGCCCTGGAACCAACGG
AGAAACAATATGCGGTTGGAGTAAAGAT
TGTTATCCCATATGGAATTATAAATACGGCACTAATGCAAGCCCAT
CGTTGTGCCAGTCTGCTC
AACGGCTAGAAGCTGGTA"""))