def tran(s,t):
    transition = 0
    transversion = float(0)
    for i in range(len(s)):
        if s[i] == t[i]:
            continue
        elif s[i] == 'A' and (t[i] == 'C' or t[i] == 'T'):
            transversion += 1
        elif s[i] == 'G' and (t[i] == 'C' or t[i] == 'T'):
            transversion += 1
        elif s[i] == 'C' and (t[i] == 'A' or t[i] == 'G'):
            transversion += 1
        elif s[i] == 'T' and (t[i] == 'A' or t[i] == 'G'):
            transversion += 1
        else:
            transition += 1

    print (transition/transversion)


tran('CCGGGTAATTATAAACAGTTTTGGGGTGGCCCACACTTTTACGGATTAACCTCTCGACCGTAAGTCTATCACCTCTCCTAGCACATGGACCGGGTACGTCTAGATTGGAATTGAGCACCTGGGTGCCCGTAGCTCTCATGCCCGACGCTAGCGCACCTTAGAAGTGTGCTTAACTTCCTGGCACTCGAACATTATGCCATTGTTCGGGTGTTTCACATAGTGTCAAATTGGACCCGGACTAGAACTTATCATCTTTCTTAAAACCAATTAGATGTAAGACCGTTAGTTAGGTTCGTTGACGGCTCACTGGCTATTCTTCGCGGGGCCCTCTGATCCAAGCGACTCAAAGTCGAGTAGGGTTGGTAACTGATGTTCTGAAGTTAGAATTTCCTGCTCCTGATAATAGTGCGATGAGTTTCAGTTCATTACTTCGGAGGGAATATTTAGTTTCTAGTACTGACATTCGGTCCCCACCCGCAATGATCACAAATTTACTTGTAATAATTCCTATCTCGTTGTGGTTCAGCAGAACAGGACGAAGTCCAATTACTTGCAGTTAGTTGGAGCCAACGGTCCACAGAATGCAGGAAAAACCATTAGGGCGACGTGACGAGGATGAGTGAGGCACCTAGAAGGCAATAATACGATAGCGGGCCATTTAAGTAGTGACCGAGCGCATCATAAAAGTATAGCCACCGCCATGCGTTATTCTCTGGTGACTGACCGTAGAAGAGTTTTACTCACGCCACGCTCAATGTACAGAAATGTACCTGAAACGTGGAATTTATCACCAGACGTCCTGCCGCAAGTTGTAAATTCCTGGCTACATAACTGAGTCTCTATAGCACCTCGTCCTGCCAAGCGATAAGGCTTTGACAGAGGTAAGATTGCCCTGGGTGCCATGTTCCGGCTGATTGGTCG','CTGTGTGAACATGAATAGTTCTTGCGCAGTCGATACATCTACGGACTATCCTCTCGACCAAAAATTTAGCACCTCCCCTAGCACGGGGAGCTGGAACGTCTGGATTAAAACTTCATACATCAGCACCCGGAGTTTCCATGCGCAATGCTAGCGCACCTTAGAGGCGCGCCTGAGTTACTGGTACTTAAACATTACCCAATTATTCGAGCAGTTCACAAAGCGTCACATTGGACTCGAACTATAGCTCACCAACTTTCCCAATTTCAATTGGATGTAAGGCCGCTAGTTGGCCTCACGGTCGGCTTAGTGGTTCTTCTTCGCGTGTTCCCTTGACCCTAGTCAAGTAGGGTCGAGTAGGGTTGATAACCGAAGTGCCGAAGTTTGAACTCTTGGTTTTTGATAACAGTACGATGATTTTACTCTCATTACTCCGCAAAGGCTATTTGGTGCCAAGCTCTGACATCCGACACCTACTCGCAATGGTCGCAAAGCCGTCTGAGGTAGTTCCTATCGTGTTGGGAACCAGGGGAATCGCACAGTGCCTGATTACTTGCAGTCGGCTGGACCCAACTATCCGTGGAGTATCAGAAACAACATTAGGGCAACGTGATGAGGATAAGCGAGGCGTCCAGAAGGCAATTACACGATAGCGGGCTATTTAAATGGTAACCGAACGCACCGTGACGGACTAGCGCCCGCCAAGTAGTGTGCGCCGGTGGCCGGATGTAGTAGAGTTCTACTCATCCCACACTCGATGTACAGGAGCGTATCCGAAGCACGGAATGTATCATTCCGCGTCCCACCGTTAGCCGTAACTTTTGGGTCTCGTAACTGAGTCTCTGTTGCGCTCCACCCTCTTAAGCGGCAAAACTTTAACTGGGTTCGACTTGCATTGCGGGACATAATCCGATCGATTGGTCG')